/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Code.*;
import java.awt.Color;
import java.util.Random;

/**
 *
 * @author muaaz
 */
public class GameUI extends javax.swing.JFrame {

    public String palindromeWords[];
    public String normalWords[];
    public String cardLabels[];
    
    /**
     * Creates new form GameUI
     */
    public GameUI() {
        initComponents();
        cardLabels = new String[4];
       
        normalWords = new String []{"Assume","At","Attack","Attention" ,"Attorney",
            "Audience","Author","Authority","Available",
        "Body", "Book" ,"Born","Both","Box","Boy","Break","Bring","Brother","Budge",
        "Concern","Condition","Conference","Congress","Consider","Contain","Continue",
        "Control","Cost","Could","Die",
        };
        
        palindromeWords   = new String[] {"Anna","Civic","Kayak","Level","Madam","Mom",
        "Noon","Racecar","Radar","Redder","Refer","Repaper",
        "Rotator","Rotor","Sagas","Solos","Stats","Tenet","Wow","Succus","Tallat","Terret","Tirrit",
        "Deified","Hadedah","Halalah","Reifier","Reviver","Rotator","Rotavator"
        };
        
        loadCards();
    }
    
    public int[] shuffleArray() {
        int[] numbers = {1, 2, 3, 4};
    Random rand = new Random();
    for (int i = 0; i < numbers.length; i++) {
        int randomIndex = i + rand.nextInt(numbers.length - i);
        int temp = numbers[i];
        numbers[i] = numbers[randomIndex];
        numbers[randomIndex] = temp;
    }
    return numbers;
    }
    
    public void loadCards() {
        Random rand = new Random();

    String palindrome = palindromeWords[rand.nextInt(palindromeWords.length)];

    String[] selectedNormalWords = new String[3];
    for (int i = 0; i < 3; i++) {
        selectedNormalWords[i] = normalWords[rand.nextInt(normalWords.length)];
    }

    int[] positions = shuffleArray();

    cardLabels[positions[0] - 1] = palindrome;
    for (int i = 1; i < 4; i++) {
        cardLabels[positions[i] - 1] = selectedNormalWords[i - 1];
    }

    btnWord1.setText(cardLabels[0]);
    btnWord2.setText(cardLabels[1]);
    btnWord3.setText(cardLabels[2]);
    btnWord4.setText(cardLabels[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnWord2 = new javax.swing.JButton();
        btnWord3 = new javax.swing.JButton();
        btnWord1 = new javax.swing.JButton();
        btnWord4 = new javax.swing.JButton();
        btnTryAgain = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Palindrome App");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/bee.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(980, 980));
        jLabel2.setMinimumSize(new java.awt.Dimension(980, 980));
        jLabel2.setPreferredSize(new java.awt.Dimension(980, 980));

        btnWord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWord2MouseClicked(evt);
            }
        });

        btnWord3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWord3MouseClicked(evt);
            }
        });

        btnWord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWord1MouseClicked(evt);
            }
        });

        btnWord4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWord4MouseClicked(evt);
            }
        });

        btnTryAgain.setText("Let's Try Again");
        btnTryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryAgainActionPerformed(evt);
            }
        });

        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnTryAgain)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnWord3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWord4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWord2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnWord2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnWord3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWord4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTryAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWord1MouseClicked
        // TODO add your handling code here:
        PalindromeChecker p = new PalindromeChecker();
        if (p.check(btnWord1.getText())) {
            btnWord1.setBackground(Color.GREEN);
            lblMessage.setText("Well done!!!");
        } else {
            btnWord1.setBackground(Color.RED);
            lblMessage.setText("Oops, Let's Try Again");
        }
    }//GEN-LAST:event_btnWord1MouseClicked

    private void btnWord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWord2MouseClicked
        // TODO add your handling code here:
        PalindromeChecker p = new PalindromeChecker();
        if (p.check(btnWord2.getText())) {
            btnWord2.setBackground(Color.GREEN);
            lblMessage.setText("Well done!!!");
        } else {
            btnWord2.setBackground(Color.RED);
            lblMessage.setText("Oops, Let's Try Again");
        }
    }//GEN-LAST:event_btnWord2MouseClicked

    private void btnWord3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWord3MouseClicked
        // TODO add your handling code here:
        PalindromeChecker p = new PalindromeChecker();
        if (p.check(btnWord3.getText())) {
            btnWord3.setBackground(Color.GREEN);
            lblMessage.setText("Well done!!!");
        } else {
            btnWord3.setBackground(Color.RED);
            lblMessage.setText("Oops, Let's Try Again");
        }
    }//GEN-LAST:event_btnWord3MouseClicked

    private void btnWord4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWord4MouseClicked
        // TODO add your handling code here:
        PalindromeChecker p = new PalindromeChecker();
        if (p.check(btnWord4.getText())) {
            btnWord4.setBackground(Color.GREEN);
            lblMessage.setText("Well done!!!");
        } else {
            btnWord4.setBackground(Color.RED);
            lblMessage.setText("Oops, Let's Try Again");
        }
    }//GEN-LAST:event_btnWord4MouseClicked

    private void btnTryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryAgainActionPerformed
        // TODO add your handling code here:
        btnWord1.setText("");
        btnWord2.setText("");
        btnWord3.setText("");
        btnWord4.setText("");
        btnWord1.setBackground(Color.WHITE);
        btnWord2.setBackground(Color.WHITE);
        btnWord3.setBackground(Color.WHITE);
        btnWord4.setBackground(Color.WHITE);
        loadCards();
    }//GEN-LAST:event_btnTryAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTryAgain;
    private javax.swing.JButton btnWord1;
    private javax.swing.JButton btnWord2;
    private javax.swing.JButton btnWord3;
    private javax.swing.JButton btnWord4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
